---
title: iSpy - An Interactive Visual Application for Exploring GAStech Employees Movement Data and Aliba, Kronos Events
author:
  - name: Hong Yun Ting
    email: ythong.2019@mitb.smu.edu.sg
    affiliation: Singapore Management University
  - name: Li ShuXian
    email: bob@example.com
    affiliation: Singapore Management University
  - name: Yang Xu
    email: xu.yang.2020@mitb.smu.edu.sg
    affiliation: Singapore Management University
abstract: |
  Leveraging on the power of visual analytics, this paper discusses the development of a prototype of interactive web application using Rshiny. With the focus of enabling efficient investigations, the prototype aims to transform information of various data formats into insightful visuals using the analytical approaches.

column_numbers: 3
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: false
bibliography: packages.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

The local company GAStech reported missing employees while multiple major outbreaks struck the city on the night of 23rd. To investigate the incidents, multiple sources of evidences have been collated:
1. GAStech released a tracking data of 2 weeks leading up to the disappearance as GAStech provides many of their employees with company cars for personal and professional use. GAStech also provided credit card transaction and Kronos-Kares loyalty card usage data.
2. Relevant microblog records that have been identified by automated filters and text transcripts of emergency dispatches by the Abila, Kronos local police and fire departments.

# Objectives
1. To reveal city location hot-spots based on the spending data and to detect spending anomaly. Investigators are able to scale down the scope of analysis with more focus on specific segments with the use of selections. 
2. To create an interactive map visualization framework that supports selection of time frame as well as employees. Movement patterns of one or more employees are displayed to discover abnormal behaviors and unofficial relationships.
3. To build a timeline analysis for the chaotic night on 23rd based on text analytics. Leveraging on topic modelling techniques are extracted from the massive amount of text data to help investigators form better understanding on the occurrence of events.

# Methods



# Results





# Conclusion
In this work we presented an integrated visual analytics dashboard for public and government analysis of tracking data, history of credit card, loyalty card and social media data. Multiple text mining, visualisation techniques were applied to further investigate things happened in Abila city in 2014. Abnormal behaviors were discovered. 

# Acknowledgement 

The authors would like to thank Professor Kam Tin Seong for his kind support and guidance on the project. 

